### ISSUE TITLE
[Bug][Trouble understanding]:What is the seed ?

### ISSUE THREAD

**Issue by aime-risson** [archethic-foundation/aeweb-cli#23]
### What happened?

I've been trying to use the aeweb cli but I dont really understand what the seed is corresponding to in the command:
`aeweb deploy-file --seed=myseedphrase ...`

Is it the seed phrase of my wallet ?
I've tried with my seed phrase (wallet created with ArchEthic Wallet) but the transaction never went trough. I do have UCOs on my wallet.

I would also suggest to throw an error when the transaction fails because for now we have no idea if it worked or not.

When logging the transactions response I get: `{ status: 'error - transaction may be invalid' }`

### What is expected ?

The transaction should work and the file should be deployed.

Thanks for the help !

**Comment by manujuniris** [comment]
Hello 

Seed can be any string by your choice.

For step by step tutorial, please check the aeweb video -
[https://www.youtube.com/watch?v=WH-0bZeeHsY&t=2s](url)
For more details - 
[https://archethic.net/lab.html](url)

Thanks

**Comment by manujuniris** [comment]
> ### What happened?
> I've been trying to use the aeweb cli but I dont really understand what the seed is corresponding to in the command: `aeweb deploy-file --seed=myseedphrase ...`
> 
> Is it the seed phrase of my wallet ? I've tried with my seed phrase (wallet created with ArchEthic Wallet) but the transaction never went trough. I do have UCOs on my wallet.
> 
> I would also suggest to throw an error when the transaction fails because for now we have no idea if it worked or not.
> 
> When logging the transactions response I get: `{ status: 'error - transaction may be invalid' }`
> 
> ### What is expected ?
> The transaction should work and the file should be deployed.
> 
> Thanks for the help !

Hello

Seed can be any string by your choice.

For step by step tutorial, please check the aeweb video -
https://www.youtube.com/watch?v=WH-0bZeeHsY&t=2s
For more details -
https://archethic.net/lab.html

Thanks

**Comment by aime-risson** [comment]
Thanks for the quick answer.
There is something I dont understand, I can't use my wallet to pay for the fees ? 
Every new file needs its own transaction chain ?

Thanks again

**Comment by samuel-uniris** [comment]
Hi @aime-risson.

In fact, this CLI deploys a file on the archethic network using a seed to forge a transaction.
This seed can be any (your funds wallets, dedicated one, ...) but the thing because it's using a transaction chain, every new transaction will be the reference of the chain.

For example:
1st transaction: transfer of UCO
2nd transaction: AEWeb deployment
3rd transaction: transfer of UCO

If you want to manage the updates of your assets on chain, the best would be to have a dedicated chain for your deployed assets, for example:
1st transaction: index.html v1
2nd transaction: index.html v2
3rd transaction: index.html v3

So the nodes would be able to fetch the last transaction of the index.html to serve clients.
